"""name

Revision ID: 455e1e28a474
Revises: 
Create Date: 2024-07-28 17:25:49.210927

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "455e1e28a474"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.Column(
            "predict",
            postgresql.ENUM(
                "unknown", "frstTeamWin", "scndTeamWin", name="matchresult"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM("unknown", "win", "lose", name="betstatus"),
            nullable=False,
        ),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column(
            "currency",
            postgresql.ENUM("USD", "EUR", name="currencytype"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bets_created"), "bets", ["created"], unique=False)
    op.create_index(op.f("ix_bets_updated"), "bets", ["updated"], unique=False)
    op.create_table(
        "matches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("planned", "ongoing", "finished", name="matchstatus"),
            nullable=False,
        ),
        sa.Column(
            "result",
            postgresql.ENUM(
                "unknown", "frstTeamWin", "scndTeamWin", name="matchresult"
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_matches_created"), "matches", ["created"], unique=False)
    op.create_index(op.f("ix_matches_updated"), "matches", ["updated"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_matches_updated"), table_name="matches")
    op.drop_index(op.f("ix_matches_created"), table_name="matches")
    op.drop_table("matches")
    op.drop_index(op.f("ix_bets_updated"), table_name="bets")
    op.drop_index(op.f("ix_bets_created"), table_name="bets")
    op.drop_table("bets")
    # ### end Alembic commands ###
