"""empty message

Revision ID: 7a47774cd5b2
Revises: 455e1e28a474
Create Date: 2024-07-28 18:23:04.264977

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a47774cd5b2"
down_revision: Union[str, None] = "455e1e28a474"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bets", sa.Column("match_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "bets", "matches", ["match_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bets", type_="foreignkey")
    op.drop_column("bets", "match_id")
    # ### end Alembic commands ###
